### ISSUE TITLE
Cycle Private Keys

### ISSUE THREAD

**Issue by pietervdvn** [covid-be-app/cwa-server#36]
Your private key leaked:

https://github.com/covid-be-app/cwa-server/blob/54b6e17f018b1fcdb10b1da3aba1cf572623fe5b/services/distribution/src/test/resources/application.yaml#L17

**Comment by ddewaele** [comment]
this is a key used during unit testing (test/resources) ... not used in an actual deployment / environment.

**Comment by pietervdvn** [comment]
Allright, a non-issue thus.
