### ISSUE TITLE
Please don't publish your security

### ISSUE THREAD

**Issue by franklouwers** [covid-be-app/cwa-server#37]
https://github.com/covid-be-app/cwa-server/blob/master/services/distribution/src/test/resources/application.yaml#L17 

Rationale for creating an issue instead of mailing:

1. The issue has been discussed publicly on Twitter, so the issue has been disclosed and is hence known
2. I want to make sure the devs get this :)

**Comment by franklouwers** [comment]
My apologies, on further inspection, this appears to be test code. Closing this issue as I assume your production keys are not your test keys ;)

**Comment by ddewaele** [comment]
It is indeed a key used during unit testing (test/resources) ... It is not used in an actual deployment / environment.

The german codebase also has a key in the repo that is used for testing purposes. (https://github.com/corona-warn-app/cwa-server/blob/master/docker-compose-test-secrets/private.pem)

FYI, actual keys are stored in a corporate 1-password vault with limited access, and stored on the runtime infrastructure in a secure vault (again with limited access) for the services to consume

**Comment by franklouwers** [comment]
Thanks for clarifying Davy, and again my apologies for jumping to conclusions based on 2nd hand info. I should have verified first. Keep up the good work!

**Comment by ddewaele** [comment]
No worries Frank ! I appreciate all feedback and I knew it was coming. In this case it is a trade-off between ease-of-development and the risks of having these type of discussions (that I don't really mind).
